services:
  - type: web
    name: hdfc-email-extractor
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: IMAP_HOST
        value: imap.gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RESEND_API_KEY
        sync: false

